// import { Geist, Geist_Mono } from "next/font/google";
import Footer from "./compontents/common/Footer";
import Header from "./compontents/common/Header";
import "./globals.css";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">

        <Header />

        {children}

        <Footer />

      </body>
    </html>
  );
}
